### ISSUE TITLE
replace read_bnd_cond_structure()

### ISSUE THREAD

**Issue by markolipka** [Davidatlarge/REC_R#2]
This function seems to be a very strange workaround to read variables from a parent environment into `calculate_diff_operator_matrix_aequi_dist_grid_variable_coeff()`.
This should be rather done by passing the needed values as arguments to the function.

**Comment by Davidatlarge** [comment]
Done. The function `read_bnd_cond_structure()` is not used anymore. The values are passed as list elements. Could still be less complicated, e.g. by passing the list elements directly to calculations in `calculate_diff_operator_matrix_aequi_dist_grid_variable_coeff()`, rather than defineing them as individual objects.
